
version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=${DB_USERNAME}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
          - POSTGRES_DB=${DB_DATABASE}
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
